# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: aljacque <aljacque@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/09/16 20:40:32 by aljacque          #+#    #+#              #
#    Updated: 2018/09/16 20:42:06 by aljacque         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_advanced_do-op
SRCS = advanced_doop.c ft_atoi.c ft_add.c ft_sub.c ft_mul.c ft_div.c ft_mod.c ft_usage.c
FLAG = -Wall -Werror -Wextra


all:
	gcc $(FLAG) $(SRCS) -o $(NAME)
clean:
	/bin/rm -f $(NAME)
re:
	clean all
